apiVersion: v1
appVersion: 1.0.49
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/master/images/java.png
name: dukecon-pwa
version: 1.0.49
